### ISSUE TITLE
Error looking for aurelia.js

### ISSUE THREAD

**Issue by The1nternet** [gooy/aurelia-compiler#1]
When I import the compiler like this:

import {Compiler} from 'gooy/aurelia';

And then try to run that module in the browser, I get this error:

GET http://localhost:9000/dist/gooy/aurelia.js 404 (Not Found)

**Comment by The1nternet** [comment]
sorry, i edited to include the full error, which is a 404 (Not Found).

**Comment by Aaike** [comment]
Hi , are you using `import {Compiler} from 'gooy/aurelia-compiler'` ? 

Also make sure `gooy/aurelia-compiler` is inside your config.js

**Comment by The1nternet** [comment]
Okay, i corrected that, but now whenever I call .compile, I get this error:

TypeError: Cannot read property '__observers__' of undefined {stack: (...), message: "Cannot read property '__observers__' of undefined"}

It looks like this is unrelated to the comipler, but if I remove the call to .compile, this error goes away.
