### ISSUE TITLE
compile method is not compiling

### ISSUE THREAD

**Issue by capaj** [gooy/aurelia-compiler#3]
I am using the compile method in my project to compile a piece of DOM in the leaflet map view.
you can check out the code here:
https://github.com/capaj/postuj-hovna/blob/d493d78e61094e4f7be274a9e336f72b64f720a8/www/components/map.js#L90

I would expect this to compile a DOM which has my map-popup-content behaviour and trigger that behaviour. Instead nothing happens, not even a console error. Am I doing something wrong?

**Comment by Aaike** [comment]
Hi i will have to investigate when i get some time. But having a quick look at it , i'm not sure if you should be compiling the leaflet ?

You should only compile elements that are associated with a view model or custom element.
so effectively , the element should be compilable by Aurelia to begin with.
I don't think you can do that with a marker created from a leaflet , as it is not an Aurelia compilable element.

Most likely you need to create a VM for your leaflet , like `my-marker.js`
Have a class in it that is named `MyMarker`
make sure it is available in the VM where you are trying to compile it (either through a `<require>` or a `globalizeResources`)

So first try the element you are trying to compile without the compiler and see if Aurelia compiles it correctly on it's own.

If it does then then you should be able to compile that element like this.
```
var marker = document.createElement("my-marker");
this.element.appendChild(marker);
this.compiler.compile(marker);
```

**Comment by capaj** [comment]
@Aaike my usecase is with popups. On the map, you can have a popup and put any HTML into it's content. I wanted to create custom element, put it there and then compile it. I am requiring the element in the map.html, so it should be available in the VM.

This is what I get when I compile: [Imgur](http://i.imgur.com/0InDDBN.png)

**Comment by capaj** [comment]
@Aaike finally after globalizing my behaviour, I was able to get my custom element to compile. Itwould probably be good to mention in the docs that views have associated behaviors and that they are not inherited from parent.
